version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
    volumes:
      - .:/app
    command: pytest tests

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"