version: '3.8'

services:
  redis:
    image: redis:7.2-alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3

  app:
    build: 
      context: .
      dockerfile: Dockerfile
    environment:
      - REDIS_HOST=redis
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - CELERY_BROKER_URL=redis://redis:6379/0
      - PYTHONPATH=/app
    depends_on:
      redis:
        condition: service_healthy
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    restart: unless-stopped
    command: uvicorn main:app --host 0.0.0.0 --port 8000

  celery-worker:
    build: 
      context: .
      dockerfile: Dockerfile
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - PYTHONPATH=/app
    command: celery -A config.celery worker --loglevel=info
    depends_on:
      - redis
      - app
    volumes:
      - .:/app
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "celery", "-A", "config.celery", "inspect", "ping"]
      interval: 30s
      timeout: 10s

volumes:
  redis_data: